#-------------------------------------------------------------------------
#
# $PostgreSQL: pgsql/src/backend/utils/mb/conversion_procs/latin2_and_win1250/Makefile,v 1.4 2007/02/09 15:55:58 petere Exp $
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/latin2_and_win1250
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= latin2_and_win1250

include $(srcdir)/../proc.mk
