#-------------------------------------------------------------------------
#
# src/backend/utils/mb/conversion_procs/euc_kr_and_mic/Makefile
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/euc_kr_and_mic
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= euc_kr_and_mic
PGFILEDESC	= "euc_kr <-> mic text conversions"

include $(srcdir)/../proc.mk
