#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/time
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /cvsroot/pgsql/src/backend/utils/time/Attic/Makefile.inc,v 1.1.1.1 1996/07/09 06:22:10 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= tqual.c
