#-------------------------------------------------------------------------
#
# src/backend/utils/mb/conversion_procs/utf8_and_euc_kr/Makefile
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_euc_kr
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= utf8_and_euc_kr

include $(srcdir)/../proc.mk
