#-------------------------------------------------------------------------
#
# src/backend/utils/mb/conversion_procs/utf8_and_iso8859/Makefile
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_iso8859
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= utf8_and_iso8859

include $(srcdir)/../proc.mk
