#define	PGTYPES_NUM_OVERFLOW		201
#define PGTYPES_NUM_BAD_NUMERIC		202
#define PGTYPES_NUM_DIVIDE_ZERO		203

#define PGTYPES_DATE_BAD_DATE		210
#define PGTYPES_DATE_ERR_EARGS		211
#define PGTYPES_DATE_ERR_ENOSHORTDATE	212
#define PGTYPES_DATE_ERR_ENOTDMY	213
#define PGTYPES_DATE_BAD_DAY		214
#define PGTYPES_DATE_BAD_MONTH		215

#define PGTYPES_TS_BAD_TIMESTAMP	220

#define PGTYPES_INTVL_BAD_INTERVAL	230

