#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for test suites
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    src/test/Makefile
#
#-------------------------------------------------------------------------

.DEFAULT:
	$(MAKE) -C regress $@
