#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for test suites
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /cvsroot/pgsql/src/test/Makefile,v 1.2 1996/11/12 11:42:41 bryanh Exp $
#
#-------------------------------------------------------------------------

.DEFAULT all:
	$(MAKE) -C bench $@
	$(MAKE) -C regress $@
