#-------------------------------------------------------------------------
#
# $PostgreSQL: pgsql/src/backend/utils/mb/conversion_procs/latin_and_mic/Makefile,v 1.4 2007/02/09 15:55:58 petere Exp $
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/latin_and_mic
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= latin_and_mic

include $(srcdir)/../proc.mk
