#! /bin/sh
# Utility to remove manufacturer's oui table
# $PostgreSQL: pgsql/contrib/mac/dropoui,v 1.2 2006/03/11 04:38:30 momjian Exp $


args=

while [ $# -gt 0 ]
do
    case "$1" in
    --help)
        echo "Usage: $0 dbname"
        exit
        ;;
    *)
        args="$args $1"
        ;;
    esac
    shift
done

psql $args <<EOF
drop function manuf(macaddr);
drop table macoui;
EOF

exit
