#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/prep
#
# IDENTIFICATION
#    src/backend/optimizer/prep/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/prep
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	prepjointree.o \
	prepqual.o \
	preptlist.o \
	prepunion.o

include $(top_srcdir)/src/backend/common.mk
