#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for JIT code that's provider independent.
#
# Note that the LLVM JIT provider is recursed into by src/Makefile,
# not from here.
#
# IDENTIFICATION
#    src/backend/jit/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/jit
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	jit.o

include $(top_srcdir)/src/backend/common.mk
