#-------------------------------------------------------------------------
#
# src/backend/utils/mb/conversion_procs/euc_cn_and_mic/Makefile
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/euc_cn_and_mic
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= euc_cn_and_mic

include $(srcdir)/../proc.mk
