#-------------------------------------------------------------------------
#
# src/backend/utils/mb/conversion_procs/utf8_and_johab/Makefile
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_johab
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= utf8_and_johab

include $(srcdir)/../proc.mk
