#!/usr/bin/perl

use lib '../../backend/catalog/';
use Catalog;

use strict;
use warnings;

my @input_files = (glob("pg_*.h"), qw(indexing.h toasting.h));

my $oids = Catalog::FindAllOidsFromHeaders(@input_files);

my %oidcounts;

foreach my $oid (@{$oids})
{
	$oidcounts{$oid}++;
}

my $found = 0;

foreach my $oid (sort { $a <=> $b } keys %oidcounts)
{
	next unless $oidcounts{$oid} > 1;
	$found = 1;
	print "$oid\n";
}

exit $found;
