.\" This is -*-nroff-*-
.\" XXX standard disclaimer belongs here....
.\" $Header: /cvsroot/pgsql/doc/man/Attic/files.5,v 1.1.1.1 1996/08/18 22:14:24 scrappy Exp $
.TH INFORMATION FILES 01/23/93 Postgres95 Postgres95
.SH "Section 8 \(em Files"
.SH "General Information"
.SH OVERVIEW
This section describes
some of the important files used by Postgres.
.SH NOTATION
\*(lq.../\*(rq at the front of file names represents the path to the
postgres user's home directory.  Anything in square brackets
.RB (\*(lq "[" \*(rq
and
.RB \*(lq "]" \*(rq)
is optional.
Anything in braces
.RB (\*(lq "{" \*(rq
and
.RB \*(lq "}" \*(rq)
can be repeated 0 or more times.  Parentheses
.BR (\*(lq "(" \*(rq
and
.BR \*(lq ")" \*(rq)
are used to group boolean expressions.
.BR |
is the boolean operator
.SM OR\c
\&.
.SH BUGS
The descriptions of
.nf
 .../data/PG_VERSION,
 .../data/base/*/PG_VERSION,
.fi
the temporary sort files, and the database debugging trace files are
absent.
