drop table Íªß©Ñ¦¿ë¾î;
create table Íªß©Ñ¦¿ë¾î (¿ë¾î text, ÝÂ×¾ÄÚµå varchar, ºñ°í1A¶ó±¸ char(16));
create index Íªß©Ñ¦¿ë¾îindex1 on Íªß©Ñ¦¿ë¾î using btree (¿ë¾î);
create index Íªß©Ñ¦¿ë¾îindex2 on Íªß©Ñ¦¿ë¾î using hash (ÝÂ×¾ÄÚµå);
insert into Íªß©Ñ¦¿ë¾î values('ÄÄÇ»ÅÍµð½ºÇÃ·¹ÀÌ', 'Ñ¦A01ß¾');
insert into Íªß©Ñ¦¿ë¾î values('ÄÄÇ»ÅÍ±×·¡ÇÈ½º', 'ÝÂB10ñé');
insert into Íªß©Ñ¦¿ë¾î values('ÄÄÇ»ÅÍÇÁ·Î±×·¡¸Ó', 'ìÑZ01ù»');
vacuum Íªß©Ñ¦¿ë¾î;
select * from Íªß©Ñ¦¿ë¾î;
select * from Íªß©Ñ¦¿ë¾î where ÝÂ×¾ÄÚµå = 'ìÑZ01ù»';
select * from Íªß©Ñ¦¿ë¾î where ÝÂ×¾ÄÚµå ~* 'ìÑz01ù»';
select * from Íªß©Ñ¦¿ë¾î where ÝÂ×¾ÄÚµå like '_Z01_';
select * from Íªß©Ñ¦¿ë¾î where ÝÂ×¾ÄÚµå like '_Z%';
select * from Íªß©Ñ¦¿ë¾î where ¿ë¾î ~ 'ÄÄÇ»ÅÍ[µð±×]';
select * from Íªß©Ñ¦¿ë¾î where ¿ë¾î ~* 'ÄÄÇ»ÅÍ[µð±×]';
select *,character_length(¿ë¾î) from Íªß©Ñ¦¿ë¾î;
select *,octet_length(¿ë¾î) from Íªß©Ñ¦¿ë¾î;
select *,position('µð' in ¿ë¾î) from Íªß©Ñ¦¿ë¾î;
select *,substring(¿ë¾î from 3 for 4) from Íªß©Ñ¦¿ë¾î;
