drop table ’·×’»»’µ¡’ÍÑ’¸ì;
create table ’·×’»»’µ¡’ÍÑ’¸ì (’ÍÑ’¸ì text, ’Ê¬’Îà’¥³’¡¼’¥É varchar, ’È÷’¹Í1A’¤À’¤è char(16));
create index ’·×’»»’µ¡’ÍÑ’¸ìindex1 on ’·×’»»’µ¡’ÍÑ’¸ì using btree (’ÍÑ’¸ì);
create index ’·×’»»’µ¡’ÍÑ’¸ìindex2 on ’·×’»»’µ¡’ÍÑ’¸ì using hash (’Ê¬’Îà’¥³’¡¼’¥É);
insert into ’·×’»»’µ¡’ÍÑ’¸ì values('’¥³’¥ó’¥Ô’¥å’¡¼’¥¿’¥Ç’¥£’¥¹’¥×’¥ì’¥¤','’µ¡A01’¾å');
insert into ’·×’»»’µ¡’ÍÑ’¸ì values('’¥³’¥ó’¥Ô’¥å’¡¼’¥¿’¥°’¥é’¥Õ’¥£’¥Ã’¥¯’¥¹','’Ê¬B10’Ãæ');
insert into ’·×’»»’µ¡’ÍÑ’¸ì values('’¥³’¥ó’¥Ô’¥å’¡¼’¥¿’¥×’¥í’¥°’¥é’¥Ş’¡¼','’¿ÍZ01’²¼');
vacuum ’·×’»»’µ¡’ÍÑ’¸ì;
select * from ’·×’»»’µ¡’ÍÑ’¸ì;
select * from ’·×’»»’µ¡’ÍÑ’¸ì where ’Ê¬’Îà’¥³’¡¼’¥É = '’¿ÍZ01’²¼';
select * from ’·×’»»’µ¡’ÍÑ’¸ì where ’Ê¬’Îà’¥³’¡¼’¥É ~* '’¿Íz01’²¼';
select * from ’·×’»»’µ¡’ÍÑ’¸ì where ’Ê¬’Îà’¥³’¡¼’¥É like '_Z01_';
select * from ’·×’»»’µ¡’ÍÑ’¸ì where ’Ê¬’Îà’¥³’¡¼’¥É like '_Z%';
select * from ’·×’»»’µ¡’ÍÑ’¸ì where ’ÍÑ’¸ì ~ '’¥³’¥ó’¥Ô’¥å’¡¼’¥¿[’¥Ç’¥°]';
select * from ’·×’»»’µ¡’ÍÑ’¸ì where ’ÍÑ’¸ì ~* '’¥³’¥ó’¥Ô’¥å’¡¼’¥¿[’¥Ç’¥°]';
select *,character_length(’ÍÑ’¸ì) from ’·×’»»’µ¡’ÍÑ’¸ì;
select *,octet_length(’ÍÑ’¸ì) from ’·×’»»’µ¡’ÍÑ’¸ì;
select *,position('’¥Ç' in ’ÍÑ’¸ì) from ’·×’»»’µ¡’ÍÑ’¸ì;
select *,substring(’ÍÑ’¸ì from 10 for 4) from ’·×’»»’µ¡’ÍÑ’¸ì;
drop table ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï;
create table ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï(‘Êõ‘Óï text, ‘·Ö‘Àà‘ºÅ varchar, ‘±¸‘×¢1A char(16));
create index ‘¼Æ‘Ëã‘»ú‘Êõ‘Óïindex1 on ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï using btree(‘Êõ‘Óï);
create index ‘¼Æ‘Ëã‘»ú‘Êõ‘Óïindex2 on ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï using btree(‘·Ö‘Àà‘ºÅ);
insert into ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï values('‘µç‘ÄÔ‘ÏÔ‘Ê¾‘ÆÁ','‘»úA01‘ÉÏ');
insert into ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï values('‘µç‘ÄÔ‘Í¼‘ĞÎ','‘·ÖB01‘ÖĞ');
insert into ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï values('‘µç‘ÄÔ‘³Ì‘Ğò‘Ô±','‘ÈËZ01‘ÏÂ');
vacuum ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï;
select * from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï;
select * from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï where ‘·Ö‘Àà‘ºÅ = '‘ÈËZ01‘ÏÂ';
select * from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï where ‘·Ö‘Àà‘ºÅ ~* '‘ÈËz01‘ÏÂ';
select * from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï where ‘·Ö‘Àà‘ºÅ like '_Z01_';
select * from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï where ‘·Ö‘Àà‘ºÅ like '_Z%';
select * from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï where ‘Êõ‘Óï ~ '‘µç‘ÄÔ[‘ÏÔ‘Í¼]';
select * from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï where ‘Êõ‘Óï ~* '‘µç‘ÄÔ[‘ÏÔ‘Í¼]';
select *,character_length(‘Êõ‘Óï) from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï;
select *,octet_length(‘Êõ‘Óï) from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï;
select *,position('‘ÏÔ' in ‘Êõ‘Óï) from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï;
select *,substring(‘Êõ‘Óï from 3 for 4) from ‘¼Æ‘Ëã‘»ú‘Êõ‘Óï;
drop table “Íª“ß©“Ñ¦“¿ë“¾î;
create table “Íª“ß©“Ñ¦“¿ë“¾î (“¿ë“¾î text, “İÂ“×¾“ÄÚ“µå varchar, “ºñ“°í1A“¶ó“±¸ char(16));
create index “Íª“ß©“Ñ¦“¿ë“¾îindex1 on “Íª“ß©“Ñ¦“¿ë“¾î using btree (“¿ë“¾î);
create index “Íª“ß©“Ñ¦“¿ë“¾îindex2 on “Íª“ß©“Ñ¦“¿ë“¾î using hash (“İÂ“×¾“ÄÚ“µå);
insert into “Íª“ß©“Ñ¦“¿ë“¾î values('“ÄÄ“Ç»“ÅÍ“µğ“½º“ÇÃ“·¹“ÀÌ', '“Ñ¦A01“ß¾');
insert into “Íª“ß©“Ñ¦“¿ë“¾î values('“ÄÄ“Ç»“ÅÍ“±×“·¡“ÇÈ“½º', '“İÂB10“ñé');
insert into “Íª“ß©“Ñ¦“¿ë“¾î values('“ÄÄ“Ç»“ÅÍ“ÇÁ“·Î“±×“·¡“¸Ó', '“ìÑZ01“ù»');
vacuum “Íª“ß©“Ñ¦“¿ë“¾î;
select * from “Íª“ß©“Ñ¦“¿ë“¾î;
select * from “Íª“ß©“Ñ¦“¿ë“¾î where “İÂ“×¾“ÄÚ“µå = '“ìÑZ01“ù»';
select * from “Íª“ß©“Ñ¦“¿ë“¾î where “İÂ“×¾“ÄÚ“µå ~* '“ìÑz01“ù»';
select * from “Íª“ß©“Ñ¦“¿ë“¾î where “İÂ“×¾“ÄÚ“µå like '_Z01_';
select * from “Íª“ß©“Ñ¦“¿ë“¾î where “İÂ“×¾“ÄÚ“µå like '_Z%';
select * from “Íª“ß©“Ñ¦“¿ë“¾î where “¿ë“¾î ~ '“ÄÄ“Ç»“ÅÍ[“µğ“±×]';
select * from “Íª“ß©“Ñ¦“¿ë“¾î where “¿ë“¾î ~* '“ÄÄ“Ç»“ÅÍ[“µğ“±×]';
select *,character_length(“¿ë“¾î) from “Íª“ß©“Ñ¦“¿ë“¾î;
select *,octet_length(“¿ë“¾î) from “Íª“ß©“Ñ¦“¿ë“¾î;
select *,position('“µğ' in “¿ë“¾î) from “Íª“ß©“Ñ¦“¿ë“¾î;
select *,substring(“¿ë“¾î from 3 for 4) from “Íª“ß©“Ñ¦“¿ë“¾î;
drop table test;
create table test (t text);
insert into test values('ENGLISH');
insert into test values('FRANÇAIS');
insert into test values('ESPAÑOL');
insert into test values('ÍSLENSKA');
insert into test values('ENGLISH FRANÇAIS ESPAÑOL ÍSLENSKA');
vacuum test;
select * from test;
select * from test where t = 'ESPAÑOL';
select * from test where t ~* 'espaÑol';
select *,character_length(t) from test;
select *,octet_length(t) from test;
select *,position('L' in t) from test;
select *,substring(t from 3 for 4) from test;
