drop table 計算機用語;
create table 計算機用語 (用語 text, 分類コード varchar, 備考1Aだよ char(16));
create index 計算機用語index1 on 計算機用語 using btree (用語);
create index 計算機用語index2 on 計算機用語 using hash (分類コード);
insert into 計算機用語 values('コンピュータディスプレイ','機A01上');
insert into 計算機用語 values('コンピュータグラフィックス','分B10中');
insert into 計算機用語 values('コンピュータプログラマー','人Z01下');
vacuum 計算機用語;
select * from 計算機用語;
select * from 計算機用語 where 分類コード = '人Z01下';
select * from 計算機用語 where 分類コード ~* '人z01下';
select * from 計算機用語 where 分類コード like '_Z01_';
select * from 計算機用語 where 分類コード like '_Z%';
select * from 計算機用語 where 用語 ~ 'コンピュータ[デグ]';
select * from 計算機用語 where 用語 ~* 'コンピュータ[デグ]';
select *,character_length(用語) from 計算機用語;
select *,octet_length(用語) from 計算機用語;
select *,position('デ' in 用語) from 計算機用語;
select *,substring(用語 from 10 for 4) from 計算機用語;
