#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/archive
#
# IDENTIFICATION
#    src/backend/archive/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/archive
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	shell_archive.o

include $(top_srcdir)/src/backend/common.mk
