# $Header: /cvsroot/pgsql/contrib/chkpass/Makefile,v 1.3 2001/09/06 10:49:29 petere Exp $

subdir = contrib/chkpass
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = chkpass
DATA_built = chkpass.sql
DOCS = README.chkpass

include $(top_srcdir)/contrib/contrib-global.mk
