.\" This is -*-nroff-*-
.\" XXX standard disclaimer belongs here....
.\" $Header: /cvsroot/pgsql/src/man/Attic/ipcclean.1,v 1.2 1996/12/11 00:27:50 momjian Exp $
.TH IPCCLEAN UNIX 11/05/95 PostgreSQL PostgreSQL
.SH NAME
ipcclean \(em clean up shared memory and semaphores from aborted backends
.SH SYNOPSIS
.BR "ipcclean"
.SH DESCRIPTION
.IR Ipcclean 
cleans up shared memory and semaphore space from aborted backends by
deleting all instances owned by user \*(lqpostgres\*(rq.  Only the DBA
should execute this program as it can cause bizarre behavior (i.e.,
crashes) if run during multi-user execution.  This program should be
executed if messages such as
.BR "semget: No space left on device"
are encountered when starting up the 
.IR postmaster
or the backend server.
.SH BUGS
If this command is executed while a 
.IR postmaster 
is running, the shared memory and semaphores allocated by the
.IR postmaster
will be deleted.  This will result in a general failure of the
backends servers started by that
.IR postmaster .
.PP
This script is a hack, but in the many years since it was written, no
one has come up with an equally effective and portable solution.
Suggestions are welcome.
.PP
The script makes assumption about the format of output of the
.BR ipcs
utility which may not be true across different operating systems.
Therefore, it may not work on your particular OS.
