.\" This is -*-nroff-*-
.\" XXX standard disclaimer belongs here....
.\" $Header: /cvsroot/pgsql/src/man/Attic/pg_dumpall.1,v 1.2 1997/01/23 06:01:07 momjian Exp $
.TH pg_dumpall UNIX 1/20/96 PostgreSQL PostgreSQL
.SH NAME
pg_dumpall \(em dumps out all Postgres databases into a script file
.SH SYNOPSIS
.BR pg_dumpall 
[pg_dump options]
.SH DESCRIPTION
.IR "pg_dumpall"
is a utility for dumping out all Postgres databases into one file.
It also dumps the pg_user table, which is global to all databases.
pg_dumpall creates each dumped database before loading.
pg_dumpall takes all pg_dump options, but \fB-f\fR and \fBdbname\fR
should not be used.
.SH EXAMPLES
.nf
To dump all databases (you can use pg_dump options):

	pg_dumpall -o >db.out

To reload into a fresh installation (you can use psql options):

	psql -e template1 <db.out

.fi
.SH "SEE ALSO"
pg_dump(1)
