#-------------------------------------------------------------------------
#
# $Id: Makefile,v 1.1 2002/07/16 09:25:05 ishii Exp $
#
#-------------------------------------------------------------------------
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		:= euc_tw_and_big5

SRCS += big5.c
OBJS += big5.o

include ../proc.mk
