--
-- CREATE_SCHEMA
--

CREATE SCHEMA foo;

CREATE SCHEMA IF NOT EXISTS bar;

CREATE SCHEMA baz;

-- Will not be created, and will not be handled by the
-- event trigger
CREATE SCHEMA IF NOT EXISTS baz;

CREATE SCHEMA element_test
  CREATE TABLE foo (id int)
  CREATE VIEW bar AS SELECT * FROM foo;

CREATE SCHEMA regress_schema_1
CREATE TABLE t4(
    b INT,
    a INT REFERENCES t5 DEFERRABLE INITIALLY DEFERRED NOT ENFORCED
          REFERENCES t6 DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk FOREIGN KEY (a) REFERENCES t6 DEFERRABLE)
CREATE TABLE t5 (a INT, b INT, PRIMARY KEY (a))
CREATE TABLE t6 (a INT, b INT, PRIMARY KEY (a));

DROP SCHEMA regress_schema_1 CASCADE;
