#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for blockchain functionality
#
# src/backend/blockchain/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/blockchain
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	blockchain.o 

include $(top_srcdir)/src/backend/common.mk