#-------------------------------------------------------------------------
#
# src/backend/utils/mb/conversion_procs/utf8_and_big5/Makefile
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_big5
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= utf8_and_big5
PGFILEDESC	= "utf8 <-> big5 text conversions"

include $(srcdir)/../proc.mk
