subdir = src/interfaces/ecpg/test/errors
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/$(subdir)/../Makefile.regress


TESTS = init init.c

all: $(TESTS)

