#############################################
# Makefile for integer aggregator
# Copyright (C) 2001 Digital Music Network.
# by Mark L. Woodward
# $Header: /cvsroot/pgsql/contrib/intagg/Makefile,v 1.3 2002/02/25 04:16:58 tgl Exp $

subdir = contrib/intagg
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = int_aggregate
DATA_built = int_aggregate.sql
DOCS = README.int_aggregate

include $(top_srcdir)/contrib/contrib-global.mk
