subdir = src/interfaces/ecpg/test/connect
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global
include ../Makefile.regress

TESTS = test1 test1.c \
        test2 test2.c \
        test3 test3.c \
        test4 test4.c 

all: $(TESTS)

