#-------------------------------------------------------------------------
#
# $PostgreSQL: pgsql/src/backend/utils/mb/conversion_procs/utf8_and_uhc/Makefile,v 1.3 2003/11/29 22:40:39 pgsql Exp $
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_uhc
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		:= utf8_and_uhc

include $(srcdir)/../proc.mk
