AROPT = crs
export_dynamic = -export-dynamic
rpath = -Wl,-rpath,$(libdir)
shlib_symbolic = -Wl,-Bsymbolic
allow_nonpic_in_shlib = yes
DLSUFFIX = .so
CFLAGS_SL = -fpic

%.so: %.o
	$(CC) -shared -o $@ $<

sqlmansect = 7
