AROPT = crs
rpath = -Wl,-rpath,'$(rpathdir)'

DLSUFFIX = .so
# PIC is default
CFLAGS_SL =

override CPPFLAGS += -U_NO_XOPEN4

ifneq ($(GCC), yes)
  CFLAGS += -woff 1164,1171,1185,1195,1552
endif
LDFLAGS += -Wl,-woff,15 -Wl,-woff,84

# Rule for building a shared library from a single .o file
%.so: %.o
	$(CC) $(CFLAGS) $(LDFLAGS) $(LDFLAGS_SL) -shared -o $@ $<

sqlmansect = 5sql
