AROPT = crs
export_dynamic = -Wl,-Bexport
ifeq ($(ld_R_works), yes)
rpath = -Wl,-R$(libdir)
endif
DLSUFFIX = .so
ifeq ($(GCC), yes)
CFLAGS_SL = -fpic
else
CFLAGS_SL = -K PIC
endif
ifeq ($(GXX), yes)
CXXFLAGS_SL = -fpic
else
CXXFLAGS_SL = -K PIC
endif

%.so: %.o
	$(LD) -G -Bdynamic -o $@ $<
