# src/makefiles/Makefile.solaris
rpath = -Wl,-rpath,'$(rpathdir)'

ifeq ($(with_gnu_ld), yes)
export_dynamic = -Wl,-E
endif

# Rule for building a shared library from a single .o file
%.so: %.o
	$(CC) $(CFLAGS) $< $(LDFLAGS) $(LDFLAGS_SL) -shared -o $@

sqlmansect = 5sql
