AROPT = crs
ifeq ($(with_gnu_ld), yes)
	export_dynamic = -Wl,-E
else
	export_dynamic = -Wl,-Bexport
endif

ifeq ($(ld_R_works), yes)
ifeq ($(with_gnu_ld), yes)
	rpath = -Wl,-rpath,$(libdir)
else
	rpath = -Wl,-R$(libdir)
endif
endif
shlib_symbolic = -Wl,-Bsymbolic

DLSUFFIX = .so
ifeq ($(GCC), yes)
CFLAGS_SL = -fpic
else
CFLAGS_SL = -K PIC
endif
ifeq ($(GCC), yes)
SO_FLAGS = -shared
else
SO_FLAGS = -G
endif

%.so: %.o
	$(CC) $(SO_FLAGS) -o $@ $<

sqlmansect = 5sql
