drop table Íªß©Ñ¦¿ë¾î;
create table Íªß©Ñ¦¿ë¾î (¿ë¾î text, İÂ×¾ÄÚµå varchar, ºñ°í1A¶ó±¸ char(16));
create index Íªß©Ñ¦¿ë¾îindex1 on Íªß©Ñ¦¿ë¾î using btree (¿ë¾î);
create index Íªß©Ñ¦¿ë¾îindex2 on Íªß©Ñ¦¿ë¾î using hash (İÂ×¾ÄÚµå);
insert into Íªß©Ñ¦¿ë¾î values('ÄÄÇ»ÅÍµğ½ºÇÃ·¹ÀÌ', 'Ñ¦A01ß¾');
insert into Íªß©Ñ¦¿ë¾î values('ÄÄÇ»ÅÍ±×·¡ÇÈ½º', 'İÂB10ñé');
insert into Íªß©Ñ¦¿ë¾î values('ÄÄÇ»ÅÍÇÁ·Î±×·¡¸Ó', 'ìÑZ01ù»');
vacuum Íªß©Ñ¦¿ë¾î;
select * from Íªß©Ñ¦¿ë¾î;
select * from Íªß©Ñ¦¿ë¾î where İÂ×¾ÄÚµå = 'ìÑZ01ù»';
select * from Íªß©Ñ¦¿ë¾î where İÂ×¾ÄÚµå ~* 'ìÑz01ù»';
select * from Íªß©Ñ¦¿ë¾î where İÂ×¾ÄÚµå like '_Z01_';
select * from Íªß©Ñ¦¿ë¾î where İÂ×¾ÄÚµå like '_Z%';
select * from Íªß©Ñ¦¿ë¾î where ¿ë¾î ~ 'ÄÄÇ»ÅÍ[µğ±×]';
select * from Íªß©Ñ¦¿ë¾î where ¿ë¾î ~* 'ÄÄÇ»ÅÍ[µğ±×]';
