-- JSON_EXISTS

SELECT JSON_EXISTS(NULL FORMAT JSON, '$');

-- JSON_VALUE

SELECT JSON_VALUE(NULL FORMAT JSON, '$');

-- JSON_QUERY

SELECT JSON_QUERY(NULL FORMAT JSON, '$');

-- JSON_TABLE

SELECT * FROM JSON_TABLE(NULL FORMAT JSON, '$' COLUMNS (foo text));
