#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for regress (the regression test)
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /cvsroot/pgsql/src/test/regress/sql/Attic/Makefile,v 1.2 1997/04/27 02:58:26 scrappy Exp $
#
#-------------------------------------------------------------------------

CLFILES=	create_function_1.sql create_function_2.sql copy.sql misc.sql

clean:
	rm -f $(CLFILES)
