subdir = contrib/dbsize
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = dbsize
DATA_built = dbsize.sql
DOCS = README.dbsize

include $(top_srcdir)/contrib/contrib-global.mk
