#!/bin/sh

# $PostgreSQL: pgsql/src/tools/codelines,v 1.3 2006/03/11 04:38:41 momjian Exp $

# This script is used to compute the total number of "C" lines in the release
# This should be run from the top of the CVS tree after a 'make distclean'
find . -name '*.[chyl]' | xargs cat| wc -l
