#!/usr/bin/env python3

# Helper to install additional files into the temporary installation
# for tests, beyond those that are installed by meson/ninja install.

import argparse
import shutil
import os

parser = argparse.ArgumentParser()

parser.add_argument('--datadir', type=str)
parser.add_argument('--libdir', type=str)
parser.add_argument('--install-data', type=str, nargs='*')
parser.add_argument('--install-libs', type=str, nargs='*')

args = parser.parse_args()


def copy_files(src_list: list, dest: str):
    os.makedirs(dest, exist_ok=True)

    for src in src_list:
        shutil.copy2(src, dest)


copy_files(args.install_data, args.datadir)
copy_files(args.install_libs, args.libdir)
