#!/bin/sh

# $PostgreSQL: pgsql/src/tools/make_etags,v 1.3 2006/03/11 04:38:41 momjian Exp $

trap "rm -f /tmp/$$" 0 1 2 3 15
rm -f ./TAGS
find `pwd`/ -type f -name '*.[chyl]' -print | \
  xargs etags --append -o TAGS

find . -type d -print | \
while read DIR; do
  [ "$DIR" != "." ] && ln -f -s `pwd`/TAGS $DIR
done
