#!/bin/sh

# $PostgreSQL: pgsql/src/tools/TODO2html,v 1.3 2008/04/19 12:52:51 momjian Exp $:

# Converts doc/TODO text file to doc/src/FAQ/TODO.html HTML file

[ ! -f COPYRIGHT ] && echo "Run from top of source tree" 1>&2 && exit 1

# check if txt2html is installed
txt2html -h > /dev/null 2>&1
if [ "$?" -gt 1 ]
then	echo "Cannot find txt2html." 1>&2
	echo "You must install txt2html from http://txt2html.sourceforge.net." 1>&2
	exit 1
fi

cat doc/TODO |
# lines with only whitespace throws off txt2html bullet formatting
sed 's/^[ 	][ 	]*$//' |
sed 's/^\(\* -\)\(.*\)$/\1*\2*/' |
sed 's/^\([	][	]*o -\)\(.*\)$/\1*\2*/' |
txt2html --xhtml -s 100 -p 100 --xhtml --titlefirst \
	--body_deco ' bgcolor="#FFFFFF" text="#000000" link="#FF0000" vlink="#A00000" alink="#0000FF"' \
	--caps_tag '' > doc/src/FAQ/TODO.html
